# Generated by Django 4.2 on 2026-06-17 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lokasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Jurusan')),
                ('kode', models.CharField(max_length=10, unique=True, verbose_name='Kode Jurusan')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jurusan',
                'verbose_name_plural': 'Data Jurusan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('10', 'X (Sepuluh)'), ('11', 'XI (Sebelas)'), ('12', 'XII (Dua Belas)')], max_length=2, verbose_name='Tingkat')),
                ('tahun_ajaran', models.CharField(help_text='Contoh: 2024/2025', max_length=9, verbose_name='Tahun Ajaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='kelas.jurusan', verbose_name='Jurusan')),
                ('ruangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='lokasi.lokasi', verbose_name='Ruangan')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Data Kelas',
                'ordering': ['tahun_ajaran', 'tingkat', 'jurusan__nama'],
            },
        ),
    ]
