# Generated by Django 4.2 on 2026-06-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('jenis_transaksi', models.CharField(choices=[('KELUAR', 'Peminjaman (Keluar)'), ('KEMBALI', 'Pengembalian (Masuk)'), ('MUTASI', 'Mutasi (Pindah Lokasi)'), ('PERBAIKAN', 'Perbaikan')], max_length=20, verbose_name='Jenis Transaksi')),
                ('nama_peminjam', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Peminjam/Penerima')),
                ('tujuan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tujuan/Keperluan')),
                ('tanggal_keluar', models.DateTimeField(verbose_name='Tanggal Keluar/Pinjam')),
                ('tanggal_kembali', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Kembali (Actual)')),
                ('status', models.CharField(choices=[('BERLANGSUNG', 'Sedang Berlangsung'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan'), ('TERLAMBAT', 'Terlambat Kembali')], default='BERLANGSUNG', max_length=20, verbose_name='Status')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan Tambahan')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.barang', verbose_name='Barang')),
            ],
            options={
                'verbose_name': 'Riwayat Transaksi',
                'verbose_name_plural': 'Riwayat Transaksi',
                'ordering': ['-tanggal_keluar'],
            },
        ),
    ]
