# Generated by Django 4.2 on 2026-06-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategori', '0001_initial'),
        ('lokasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('kode_aset', models.CharField(max_length=50, unique=True, verbose_name='Kode Aset')),
                ('nama_barang', models.CharField(max_length=255, verbose_name='Nama Barang')),
                ('merek', models.CharField(blank=True, max_length=100, null=True, verbose_name='Merek')),
                ('nomor_seri', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor Seri')),
                ('tanggal_pembelian', models.DateField(blank=True, null=True, verbose_name='Tanggal Pembelian')),
                ('harga_beli', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Harga Beli (Rp)')),
                ('kondisi', models.CharField(choices=[('Baru', 'Baru'), ('Baik', 'Baik'), ('Rusak Ringan', 'Rusak Ringan'), ('Rusak Berat', 'Rusak Berat')], default='Baik', max_length=20, verbose_name='Kondisi')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_barang/', verbose_name='Foto Barang')),
                ('tersedia', models.BooleanField(default=True, verbose_name='Tersedia untuk Dipinjam')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kategori.kategori', verbose_name='Kategori')),
                ('lokasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lokasi.lokasi', verbose_name='Lokasi Saat Ini')),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Data Inventaris Barang',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
