# Generated by Django 4.2 on 2026-06-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('nama_ruangan', models.CharField(max_length=100, verbose_name='Nama Ruangan')),
                ('gedung', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gedung')),
                ('lantai', models.IntegerField(blank=True, null=True, verbose_name='Lantai')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Lokasi',
                'verbose_name_plural': 'Daftar Lokasi',
                'ordering': ['gedung', 'lantai', 'nama_ruangan'],
            },
        ),
    ]
