# Generated by Django 4.2 on 2026-06-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('nama_kategori', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('kode_awal', models.CharField(help_text='Contoh: ELEK untuk Elektronik', max_length=10, unique=True, verbose_name='Kode Awal')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('induk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_kategori', to='kategori.kategori', verbose_name='Induk Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Daftar Kategori',
                'ordering': ['nama_kategori'],
            },
        ),
    ]
