# Generated by Django 4.2 on 2026-06-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalPerawatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('diperbarui_pada', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('kerusakan', models.TextField(verbose_name='Deskripsi Kerusakan')),
                ('tindakan', models.TextField(blank=True, null=True, verbose_name='Tindakan Perbaikan')),
                ('biaya', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Biaya Perbaikan')),
                ('tanggal_perbaikan', models.DateField(blank=True, null=True, verbose_name='Tanggal Perbaikan')),
                ('teknisi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Teknisi/Vendor')),
                ('status_perbaikan', models.CharField(choices=[('PENGAJUAN', 'Pengajuan'), ('PROSES', 'Sedang Diperbaiki'), ('SELESAI', 'Selesai')], default='PENGAJUAN', max_length=20, verbose_name='Status')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.barang', verbose_name='Barang')),
            ],
            options={
                'verbose_name': 'Perawatan Barang',
                'verbose_name_plural': 'Data Perawatan Barang',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
